language: go

go:
  - "1.x"

go_import_path: code.cloudfoundry.org/gcp-broker-proxy

install:
  - go get -t ./...
  - go get -u github.com/onsi/ginkgo/ginkgo
  - go install github.com/onsi/ginkgo/ginkgo
  - export PATH=$PATH:$HOME/gopath/bin
